In [1]:
## stl 로드 라이브러리 설치
# pip install numpy-stl

In [2]:
## 라이브러리 호출
import os
import numpy
from stl import mesh
import numpy as np

In [3]:
## stl 파일이 있는 위치
path = "D:/0_se"

In [4]:
## 작업 디렉토리 변경
os.chdir(path)

In [5]:
## stl파일 ctl 변수에 저장
ctl= mesh.Mesh.from_file('model.stl')

FileNotFoundError: [Errno 2] No such file or directory: 'model.stl'

In [8]:
ctl.points

array([[-2.5       , -1.        ,  0.25      , ..., -2.5       ,
        -1.        , -0.25      ],
       [ 2.5       , -1.        , -0.25      , ..., -2.5       ,
        -1.        , -0.25      ],
       [-2.5       ,  1.        , -0.25      , ..., -2.5       ,
        -1.        , -0.25      ],
       ...,
       [ 0.9667928 , -0.01011871,  0.25      , ...,  2.5       ,
         1.        ,  0.25      ],
       [ 2.5       ,  1.        , -0.25      , ...,  2.5       ,
        -1.        , -0.25      ],
       [ 2.5       , -1.        ,  0.25      , ...,  2.5       ,
         1.        ,  0.25      ]], dtype=float32)

In [9]:
ctl.points[0]

array([-2.5 , -1.  ,  0.25, -2.5 ,  1.  , -0.25, -2.5 , -1.  , -0.25],
      dtype=float32)

## 한 삼각형을 이루는 세 점들 

In [10]:
point1 = ctl.v0[0]
point2 = ctl.v1[0]
point3 = ctl.v2[0]

In [11]:
point1

array([-2.5 , -1.  ,  0.25], dtype=float32)